export const GET_FAVORITE_LIST = 'GET_FAVORITE_LIST';

export const FETCHING_LATEST = 'FETCHING_LATEST';
export const GETTING_LATEST_DATA = 'GETTING_LATEST_DATA';
export const NEXT_PAGE_PLAYING = 'NEXT_PAGE_PLAYING';
export const ERROR_LATEST = 'ERROR_LATEST';

export const  FETCHING_DATA = 'FETCHING_DATA';
export const  GETTING_DATA = 'GETTING_DATA';
export const  NEXT_PAGE = 'NEXT_PAGE';
export const  ERROR = 'ERROR';

export const  FETCHING_RATED_DATA = 'FETCHING_RATED_DATA';
export const  GETTING_RATED_DATA = 'GETTING_RATED_DATA';
export const  NEXT_PAGE_LATEST = 'NEXT_PAGE_LATEST';
export const  ERROR_RATED = 'ERROR_RATED';

export const  SEARCH_MOVIE = 'SEARCH_MOVIE';
export const  FETCHING_SEARCH = 'FETCHING_SEARCH';
export const  GETTING_SEARCH_VALUES = 'GETTING_SEARCH_VALUES';
export const  ERROR_SEARCH = 'ERROR_SEARCH';

export const  FETCHING_SINGLE_VIDEO = 'FETCHING_SINGLE_VIDEO';
export const  SAVING_SINGLE_VIDEO_ID = 'SAVING_SINGLE_VIDEO_ID';
export const  ERROR_WHILE_FETCHING_SINGLE_VIDEO = 'ERROR_WHILE_FETCHING_SINGLE_VIDEO';

export const  FETCHING_TV_DATA = 'FETCHING_TV_DATA';
export const  GETTING_TV_DATA = 'GETTING_TV_DATA';
export const  NEXT_PAGE_POPULAR = 'NEXT_PAGE_POPULAR';
export const  ERROR_TV = 'ERROR_TV';

export const  FETCHING_HEADER_VIDEO = 'FETCHING_HEADER_VIDEO';
export const  SAVING_VIDEO_ID = 'SAVING_VIDEO_ID';
export const  ERROR_WHILE_FETCHING_VIDEO = 'ERROR_WHILE_FETCHING_VIDEO';
