export const initialValue = {
  popular: [],
  tvPopular: [],
  latestRated: [],
  playingMovie: [],
  movieSearch: "",
  movieSearchResponse: [],
  loading: false,
  error: "",
  favoriteList: [],
  popularVideo: [],
  singleMovie: [],
  popularPage: 1,
  tvPopularPage: 1,
  latestRatedPage: 1,
  playingMoviePage: 1,
};
